---

- name: CONSUL_TEMPLATE | Copy Daemon script
  template:
    src: "{{ consul_template_service_template_file }}"
    dest: /etc/systemd/system/consul_template.service
    mode: 0644
    owner: root
    group: root
  notify: restart consul_template

- name: CONSUL_TEMPLATE | Configuring service
  systemd:
    name: consul_template
    state: "{{ consul_template_service_state }}"
    enabled: "{{ consul_template_service_enabled }}"
    daemon_reload: true
