---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: consul_template
    groups:
      - consul_template_group
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - '/tmp'
      - '/run'
      - '/run/lock'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: consul_network
        links:
        - consul:consul
  - name: consul
    groups:
      - consul_group
    image: consul
    privileged: false
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 8500/tcp
    published_ports:
      - 0.0.0.0:8500:8500/tcp
    tmpfs:
      - '/tmp'
    stop_signal: 'RTMIN+3'
    networks:
      - name: consul_network
        links:
        - consul_template:consul_template
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
